version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  publisher:
    build:
      context: .
      dockerfile: ./publisher/Dockerfile
    ports:
      - 8082:8082
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
    restart: always
    depends_on:
      - kafka

  consumer:
    build:
      context: .
      dockerfile: ./consumer/Dockerfile
    ports:
      - 8081:8081
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
    restart: always
    depends_on:
      - postgresql

  postgresql:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: numbers
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    restart: always
    depends_on:
      - publisher